name = "unifi-cloudflare-ddns"
account_id = "${CF_ACCOUNT_ID}"
main = "src/index.js"
compatibility_date = "204-11-19"
routes = [
    "https://ddns.pcwprops.com/*"
]

# Smart Placement
[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
