name = "unifi-cloudflare-ddns"
main = "src/index.js"
compatibility_date = "2024-11-18"

# Routes
routes = [
  { pattern = "ddns.pcwprops.com/*", custom_domain = true }
]

# Observability
[observability]
enabled = true
