name = "unifi-ddns-dm"
main = "src/index.js"
account_id = "4ec24ae312f5c61a4fcddc9ba3e9d29b"
compatibility_date = "2024-10-18"

# Custom domain setup
routes = [
  { pattern = "ddns.dynamicmarching.com/*", zone_id = "34fd4d57e09b698118febede791c1aaa" }
]
