name = "unifi-cloudflare-ddns"
main = "src/index.js"
compatibility_date = "2024-11-18"
routes = [
  { custom_domain = "ddns.pcwprops.com", zone_name = "pcwprops.com" }
]

# Observability
[observability]
enabled = true
