name = "unifi-cloudflare-ddns"
account_id = ""$[op://JuliansPi/gydlhygc33aendld6kckt5xg5i/Account ID]"
main = "src/index.js"
compatibility_date = "204-11-19"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

routes = [
    "https://ddns.pcwprops.com/*"
]