name = "unifi-cloudflare-ddns"
account_id = "4ec24ae312f5c61a4fcddc9ba3e9d29b"
main = "src/index.js"
compatibility_date = "2024-11-19"
routes = [
    "https://ddns.pcwprops.com/*"
]

# Smart Placement
[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
