name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering in the GitHub Actions UI
  repository_dispatch: # Allows triggering via API or webhooks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install the latest Wrangler version
      - name: Install Wrangler
        run: npm install -g wrangler@3.88.0

      # Step 3: Deploy to Cloudflare Workers
      - name: Deploy to Cloudflare Workers
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
