name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Install Wrangler
      run: npm install -g wrangler@3.109.1

    - name: Deploy to Cloudflare
      run: npx wrangler publish
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
